---
- name: Create Python 3 symlink
  ansible.builtin.file:
    src: "/usr/bin/python3"
    path: "/usr/bin/python"
    state: link

- name: Install pip3
  ansible.builtin.apt:
    pkg:
      - python3-pip
      - pipx

- name: Install boto3 and botocore via system packages
  ansible.builtin.apt:
    name:
      - python3-boto3
      - python3-botocore
    state: present

- name: Ensure pipx path is configured
  ansible.builtin.shell: pipx ensurepath
  become_user: "{{ ansible_user | default('ubuntu') }}"
  ignore_errors: yes
